<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\ECommerceApp.Contracts\ECommerceApp.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Shared\ECommerceApp.Shared\ECommerceApp.Shared.csproj" />
    <ProjectReference Include="..\ECommerceApp.Product.Domain\ECommerceApp.Product.Domain.csproj" />
  </ItemGroup>

</Project>
